apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2 # two pods
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers: # specify the container registry to pull the image from
      - name: simple-api
        image: ismaelbernal83/simple-node
        ports:
        - containerPort: 80
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: "1"
        #   requests:
        #     memory: 256Mi
        #     cpu: "0.2"
      # livenessProbe:
      #   httpGet:
      #     path: /health
      #     port: 8080
      #   initialDelaySeconds: 3
      #   periodSeconds: 3