apiVersion: v1
kind: Service
metadata:
  name: my-app # name of the service
  labels:
    run: my-app
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-app # pods that it will run against this service